- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.7.1
  hooks:
    - id: check-yaml
- repo: https://github.com/willthames/ansible-lint.git
  sha: v3.4.11
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$